package it.unicam.cs.enums;

public enum Permission {
    UPLOAD_PRODUCT,
    REMOVE_PRODUCT,
    PUBLISH_PRODUCT,
    ADD_TRANSFORMATION_INFO,
    REMOVE_TRANSFORMATION_INFO,
    ADD_PRODUCT_INFO,
    REMOVE_PRODUCT_INFO,
    CREATE_PRODUCT_PACKAGE,
    DELETE_PRODUCT_PACKAGE,
    EDIT_PRODUCT_PACKAGE,
}
